export const appConstants = {
  GET_CONTENT_SLOTS_SUCCESS: "GET_CONTENT_SLOTS_SUCCESS",
  UPLOAD_PRODUCT_SUCCESS: "UPLOAD_PRODUCT_SUCCESS",
  SAVE_PRODUCT_SUCCESS: "SAVE_PRODUCT_SUCCESS",
  CHANGE_PRODUCT_CODE: "CHANGE_PRODUCT_CODE",
  CHANGE_PRODUCT_NAME: "CHANGE_PRODUCT_NAME",
  CHANGE_PRODUCT_CATEGORY: "CHANGE_PRODUCT_CATEGORY",
  CHANGE_CONTENT_SLOT: "CHANGE_CONTENT_SLOT",
  SELECT_IMAGE: "SELECT_IMAGE",
  SUBMIT_FORM: "SUBMIT_FORM",
};
